import MyApp from "./_app"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Delicious Food Recipes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Body>
        <MyApp/>
      </Body>

    </div>
  )
}
